[package]
name = "game-of-life"
version = "0.0.1"
edition = "2018"

[dependencies]
itertools = "0.10.3"
tui = "0.17.0"
crossterm = "0.23.2"

[dev-dependencies]
terminal_size = "0.1.17"
rand = "0.8.4"

